
// ===================================
// DATA
// ===================================
const DATA = {
  topics: [
    {
      id: 'jdk',
      name: 'Java Basics & JDK/JRE/JVM',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Q1â€“8 in 2025 paper. Fill-in-blanks Q14â€“16. Appears every year.',
      questions: [
        { q: 'What is the difference between JDK, JRE, and JVM?', a: 'JDK (Java Development Kit) is for developers â€” includes compiler (javac) and tools. JRE (Java Runtime Environment) is for running Java programs. JVM (Java Virtual Machine) executes the bytecode. JDK includes JRE which includes JVM.' },
        { q: 'Which tool compiles Java source code?', a: '<code>javac</code> â€” it takes your .java file and compiles it into a .class bytecode file.' },
        { q: 'What does the JRE do?', a: 'The JRE provides the environment to RUN (execute) Java programs. It contains the JVM and class libraries.' },
        { q: 'What is the difference between a compiler and an interpreter?', a: 'A compiler translates the ENTIRE source code into machine code at once (before execution). An interpreter reads and executes code ONE LINE AT A TIME.' },
        { q: 'What is required after installing the JDK?', a: 'You must configure the Java PATH (environment variable) so your system can find the java and javac commands.' },
        { q: 'The command java -version checks the compiler version â€” True or False?', a: 'FALSE. <code>java -version</code> checks the JRE/JVM version. To check the compiler you use <code>javac -version</code>.' },
        { q: 'What is bytecode in Java?', a: 'Bytecode is the code generated by the Java compiler (javac). It is platform-independent and is executed by the JVM. NOT machine code â€” it is an intermediate form.' },
        { q: 'Java language was initially called as ___', a: '<strong>Oak</strong> â€” Java was originally called Oak by James Gosling at Sun Microsystems.' }
      ],
      quiz: [
        { q: 'Which tool is used to compile Java source code?', opts: ['java', 'javac', 'jar', 'javadoc'], ans: 1 },
        { q: 'What does the JRE do?', opts: ['Edit code', 'Compile code', 'Run code', 'Debug code'], ans: 2 },
        { q: 'A compiler reads one line of code at a time â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'What is required after installing JDK?', opts: ['Restart system', 'Configure Java Path', 'Format drive', 'Update BIOS'], ans: 1 },
        { q: 'Java language was initially called:', opts: ['Sumatra', 'J++', 'Oak', 'Pine'], ans: 2 },
        { q: 'What is bytecode in Java?', opts: ['Code generated by a Java compiler', 'Code generated by a JVM', 'Name of Java source file', 'Block of code inside a class'], ans: 0 },
        { q: 'Which provides the runtime environment for Java bytecode?', opts: ['JDK', 'JVM', 'JRE', 'JAVAC'], ans: 1 },
        { q: 'JVM stands for:', opts: ['Java Very Large Machine', 'Java Verified Machine', 'Java Very Small Machine', 'Java Virtual Machine'], ans: 3 },
        { q: 'JDK stands for:', opts: ['Java Dynamic Kit', 'Java Development Kit', 'Java Deployment Kit', 'Java Delvik Kit'], ans: 1 },
        { q: 'Who is known as the father of Java?', opts: ['James Gosling', 'M.P Java', 'Charles Babbage', 'Blaise Pascal'], ans: 0 },
      ]
    },
    {
      id: 'datatypes',
      name: 'Data types, Variables & Operators',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Q10â€“20 MCQ in 2025 papers. Section B Q10â€“12,17. Biggest topic cluster.',
      questions: [
        { q: 'Which of the following is NOT a primitive data type in Java?', a: 'String is NOT primitive. Primitive types are: int, double, float, long, char, boolean, byte, short. String is an object/reference type.' },
        { q: 'What is the result of 5 + 3 * 2 in Java?', a: '11 â€” Multiplication is done first (operator precedence): 3*2=6, then 5+6=11. NOT 16.' },
        { q: 'What does (double)5 / 2 return?', a: '2.5 â€” The cast (double) makes 5 into 5.0, so 5.0/2 = 2.5 (not integer division).' },
        { q: "What does char ch = 'A' + 1 assign to ch?", a: "'B' â€” Characters have ASCII values. 'A' = 65, so 65+1 = 66 = 'B'." },
        { q: 'What does casting a double to int do to the decimal part?', a: 'It TRUNCATES (cuts off) the decimal. (int)3.9 = 3, not 4. It does NOT round.' },
        { q: 'The ++ operator increases a variable\'s value by 2 â€” True or False?', a: 'FALSE. ++ increases by 1 (increment by 1). To increase by 2, use x += 2.' },
        { q: 'What is the default value of an int variable in Java?', a: '0 â€” Java instance variables have default values. int â†’ 0, boolean â†’ false, double â†’ 0.0, String/object â†’ null.' },
        { q: 'What is the default value of a boolean variable?', a: 'false â€” boolean default is false.' },
        { q: 'Given i = 1; what will int j = --i; give for i and j?', a: 'i will be 0 and j will be 0. The pre-decrement (--i) decrements i FIRST (i becomes 0), then assigns to j. So both are 0.' },
        { q: 'What will System.out.println(5 + "5"); output?', a: '"55" â€” When you add an int to a String, Java converts the int to a String and concatenates. 5 + "5" = "55".' },
        { q: 'What will System.out.println(3 == 3.0); output?', a: 'true â€” Java promotes the int 3 to double 3.0 for comparison. 3.0 == 3.0 is true.' }
      ],
      quiz: [
        { q: 'Which of the following is NOT a primitive data type in Java?', opts: ['String', 'int', 'boolean', 'double'], ans: 0 },
        { q: 'The result of 5 + 3 * 2 in Java is:', opts: ['16', '11', '13', '10'], ans: 1 },
        { q: "What does char ch = 'A' + 1 assign to ch?", opts: ["'A'", "'B'", '66', 'Error'], ans: 1 },
        { q: 'Arithmetic operations in Java ignore precedence â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'What is the default value of a boolean in Java?', opts: ['true', 'false', 'null', '0'], ans: 1 },
        { q: 'Given i=1; what does int j = --i give for i and j?', opts: ['i=0, j=1', 'i=1, j=0', 'i=1, j=1', 'i=0, j=0'], ans: 3 },
        { q: 'What is the output of System.out.println(5 + "5");', opts: ['10', '55', '5+5', 'Compilation error'], ans: 1 },
        { q: 'What is the output of System.out.println(3 == 3.0);', opts: ['true', 'false', 'Compilation error', 'NaN'], ans: 0 },
        { q: 'Which data type can store decimal values?', opts: ['int', 'char', 'boolean', 'double'], ans: 3 },
        { q: 'How do you create a constant variable in Java?', opts: ['static int x=10', 'final int x=10', 'const int x=10', 'define x=10'], ans: 1 },
        { q: 'Which is NOT a valid operator in Java?', opts: ['++', '--', '**', '%'], ans: 2 },
        { q: 'What does (double)0 / 0 return in Java?', opts: ['Infinity', 'NaN', '0', 'Exception'], ans: 1 },
      ]
    },
    {
      id: 'scanner',
      name: 'Scanner & User Input',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Q18,21,22,25 MCQ 2025. Section B Q20. Long answer Q26.',
      questions: [
        { q: 'How do you create a Scanner for console input?', a: '<code>Scanner sc = new Scanner(System.in);</code> â€” You must import java.util.Scanner first.' },
        { q: 'Which method reads an integer using Scanner?', a: '<code>sc.nextInt()</code> â€” reads the next integer from input. Other methods: <code>nextDouble()</code>, <code>next()</code> for a word, <code>nextLine()</code> for a full line.' },
        { q: 'What does input.close() do?', a: 'It closes the input stream (Scanner). Always close when done to free resources.' },
        { q: 'State one advantage and one disadvantage each of Scanner vs BufferedReader.', a: 'Scanner: Advantage = easy to use, has specific methods (nextInt, nextDouble). Disadvantage = slower, can have issues mixing nextLine with nextInt. BufferedReader: Advantage = faster. Disadvantage = more complex, requires manual parsing (Integer.parseInt), must handle IOException.' },
        { q: 'Java converts int to double using which type of conversion?', a: 'Widening conversion â€” it is automatic and requires no explicit cast. <code>int x = 5; double y = x;</code> works automatically.' }
      ],
      quiz: [
        { q: 'Which reads an integer from Scanner?', opts: ['input.readInt()', 'input.getInt()', 'input.inputInt()', 'input.nextInt()'], ans: 3 },
        { q: 'Which method accepts String input using Scanner?', opts: ['input.string()', 'input.readString()', 'input.stringInput()', 'input.next()'], ans: 3 },
        { q: 'The correct way to create a Scanner for console input is:', opts: ['new Scanner()', 'Scanner sc = new Scanner()', 'Scanner sc = new Scanner(System.in)', 'InputScanner()'], ans: 2 },
        { q: 'What does input.close() do?', opts: ['Saves input', 'Closes the input stream', 'Clears input', 'Initializes Scanner'], ans: 1 },
        { q: 'Java converts int to double using:', opts: ['Explicit casting', 'Widening conversion', 'Narrowing conversion', 'Bit shifting'], ans: 1 },
      ]
    },
    {
      id: 'strings',
      name: 'String Methods & Math Class',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Q26â€“35 MCQ 2025. Dense cluster of practical questions.',
      questions: [
        { q: 'What does Math.random() return?', a: 'A random double between 0.0 (inclusive) and 1.0 (exclusive). It does NOT return a random integer. Use <code>(int)(Math.random()*10)</code> for 0â€“9.' },
        { q: 'What does Math.floor(3.8) return?', a: '3.0 â€” floor() rounds DOWN to the nearest whole number. Returns a double.' },
        { q: "How do you access the character 'M' in the string \"James\"?", a: "<code>name.charAt(1)</code> â€” Indexing starts at 0: J=0, a=1, m=2, e=3, s=4. Note 'm' (lowercase) is at index 2. The exam's 'M' was capital â€” in the string 'James', charAt(1) gives 'a'." },
        { q: 'Which method removes whitespace from both ends of a String?', a: '<code>trim()</code> â€” e.g. "  hello  ".trim() returns "hello".' },
        { q: 'Do you need to import java.lang.Math?', a: 'FALSE â€” java.lang is automatically imported in every Java program. You never need to import it.' },
        { q: 'Which method converts "123" to an integer?', a: '<code>Integer.parseInt("123")</code> â€” returns the int value 123.' },
        { q: 'How do you compare two Strings in Java?', a: 'Use <code>.equals()</code> or <code>.compareTo()</code>. NEVER use == for content comparison â€” == checks if they are the same object in memory, not if they have the same characters.' }
      ],
      quiz: [
        { q: 'What does Math.random() return?', opts: ['A random integer', 'A random double 0.0 to <1.0', 'A random double 0.0 to 1.0', 'A random float'], ans: 1 },
        { q: 'What does Math.floor(3.8) return?', opts: ['3.0', '4.0', '3.8', '3'], ans: 0 },
        { q: 'Which method removes whitespace from both ends of a string?', opts: ['remove()', 'delete()', 'trim()', 'clean()'], ans: 2 },
        { q: 'Which method converts "123" to an integer?', opts: ['Integer.toString()', 'String.valueOf()', 'Integer.parseInt()', 'parseInteger()'], ans: 2 },
        { q: "How do you compare two Strings for content equality?", opts: ['==', '.equals()', '.same()', '.isEqual()'], ans: 1 },
        { q: 'The value of "a" < "b" evaluates to:', opts: ['true', 'false', '0', 'Error'], ans: 0 },
        { q: 'What does Math.round() do to 5.67?', opts: ['Returns 5', 'Returns 6', 'Returns 5.7', 'Returns 5.67'], ans: 1 },
      ]
    },
    {
      id: 'control',
      name: 'Control Structures (if/else, switch, loops)',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Q37â€“50 MCQ 2025. Long answer Q21 (loop), Q23 (switchâ†’if-else). Section B Q19.',
      questions: [
        { q: 'How many times does a do-while loop run if the condition is initially false?', a: 'Once (1 time). A do-while always executes the body at least once BEFORE checking the condition.' },
        { q: 'What does break do in a loop or switch?', a: 'break TERMINATES the entire loop or switch statement immediately. Execution continues after the loop/switch.' },
        { q: 'What does continue do?', a: 'continue SKIPS the current iteration and jumps to the next one. It does NOT stop the loop.' },
        { q: 'What is the result of true ^ false?', a: 'true â€” The ^ operator is XOR (exclusive OR). It returns true only when the two values are DIFFERENT.' },
        { q: 'When is switch preferred over if-else?', a: 'When the conditions are specific numeric or string MATCHES (equality checks). If you need range checks or complex logical conditions, use if-else.' },
        { q: 'Explain the difference between while and do-while loops.', a: 'while: checks condition BEFORE executing body â€” if condition is false initially, body may never run. do-while: executes body FIRST, then checks condition â€” always runs at least once.' },
        { q: 'What is the output of System.out.println(5 > 2 && 4 < 3);?', a: 'false â€” 5 > 2 is true, but 4 < 3 is false. AND (&&) requires BOTH to be true. So true && false = false.' }
      ],
      quiz: [
        { q: 'How many times does a do-while loop run if condition is initially false?', opts: ['0', '1', '2', 'Infinite'], ans: 1 },
        { q: 'What does break do in a loop?', opts: ['Skips current iteration', 'Terminates the loop/switch', 'Repeats iteration', 'Pauses execution'], ans: 1 },
        { q: '(condition1) ^ (condition2) is true if both are true â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'A while loop checks the condition AFTER executing the body â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'The output of System.out.println(5 > 2 && 4 < 3);', opts: ['true', 'false', 'Error', 'null'], ans: 1 },
        { q: 'What is the result of (true || false)?', opts: ['true', 'false', 'null', 'Error'], ans: 0 },
        { q: 'Which is used for decision making in Java?', opts: ['loop', 'switch', 'if-else', 'Both B and C'], ans: 3 },
        { q: 'continue in a loop:', opts: ['Terminates the loop', 'Skips current iteration', 'Restarts loop from beginning', 'Causes a compile error'], ans: 1 },
      ]
    },
    {
      id: 'exceptions',
      name: 'Exception Handling',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Q51â€“60 MCQ 2025. Section B Q6,7,8,20. Very consistent topic every year.',
      questions: [
        { q: 'What is the root class for all exceptions in Java?', a: 'Throwable â€” Both Exception and Error extend Throwable.' },
        { q: 'What exception does Scanner.nextInt() throw if input is a String?', a: 'InputMismatchException â€” thrown when the next token does not match the expected type.' },
        { q: 'Is the finally block skipped if an exception occurs?', a: 'FALSE â€” The finally block ALWAYS runs, whether or not an exception occurred. It is used for cleanup (like closing files).' },
        { q: 'What is the output of dividing 3.0 by 0 in Java?', a: 'Infinity â€” dividing a floating-point number by zero gives Infinity, not an error. Dividing an integer by zero (3/0) throws ArithmeticException.' },
        { q: 'What happens when an exception is not caught?', a: 'The program CRASHES (terminates abnormally) and prints a stack trace.' },
        { q: 'What is the try block?', a: 'The try block contains the statements that MAY cause (throw) an exception that you are willing to handle. If an exception occurs, control passes to the matching catch block.' },
        { q: 'Can a try block have multiple catch blocks?', a: 'YES â€” a single try block can have multiple catch blocks, each handling a different exception type.' },
        { q: 'What is the difference between Checked and Unchecked exceptions?', a: 'Checked exceptions (e.g. FileNotFoundException) must be declared or handled. Unchecked exceptions (e.g. ArrayIndexOutOfBoundsException) do not need to be declared.' }
      ],
      quiz: [
        { q: 'What is the root class for all exceptions?', opts: ['Error', 'Throwable', 'Object', 'RuntimeException'], ans: 1 },
        { q: 'What exception does Scanner.nextInt() throw for non-integer input?', opts: ['ArithmeticException', 'InputMismatchException', 'IOException', 'FileNotFoundException'], ans: 1 },
        { q: 'The finally block is skipped if an exception occurs â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'What is the output of dividing 3.0 by 0 in Java?', opts: ['Error', 'ArithmeticException', '0', 'Infinity'], ans: 3 },
        { q: 'An exception is an error that occurs during program compilation â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'A try block can have multiple catch blocks â€” True or False?', opts: ['True', 'False'], ans: 0 },
        { q: 'What will happen if a try block does not throw an exception?', opts: ['catch block runs', 'Program crashes', 'catch is skipped', 'Program exits'], ans: 2 },
        { q: 'What exception is thrown by integer division by zero?', opts: ['NullPointerException', 'ArithmeticException', 'InputMismatchException', 'RuntimeException'], ans: 1 },
      ]
    },
    {
      id: 'files',
      name: 'File Handling',
      heat: 'warm', heatLabel: 'Likely',
      why: 'Q54,55,61 MCQ 2025. Section B Q6,7. Long answer Q25.',
      questions: [
        { q: 'What is the difference between PrintWriter and the File class?', a: 'File class represents a file path/location â€” used to check if a file exists, create, delete etc. PrintWriter actually WRITES text content to a file using methods like <code>println()</code>.' },
        { q: 'Should PrintWriter.close() be called after writing?', a: 'YES â€” Always call close() to flush the buffer and properly close the file. Without it, data may not be saved.' },
        { q: 'What exception is thrown when opening a non-existent file for reading?', a: 'FileNotFoundException â€” thrown when you try to open a file that does not exist.' },
        { q: 'A file must always exist before you can write to it â€” True or False?', a: 'FALSE â€” PrintWriter can CREATE a new file if it does not exist yet.' }
      ],
      quiz: [
        { q: 'Which method writes a line to a file using PrintWriter?', opts: ['writeLine()', 'output.printLine()', 'println.output()', 'output.println()'], ans: 3 },
        { q: 'PrintWriter.close() should NOT be called after writing â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'A file must always exist before you can write to it â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'What exception is thrown when opening a non-existent file?', opts: ['IOException', 'FileNotFoundException', 'InputMismatchException', 'ArithmeticException'], ans: 1 },
      ]
    },
    {
      id: 'arrays',
      name: 'Arrays, ArrayList & Collections',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Q63â€“75 MCQ 2025. Long answer Q22 (2D array) and Q24 (Array vs ArrayList). Section C Q1.',
      questions: [
        { q: 'What is the difference between an Array and an ArrayList?', a: 'Array: FIXED size (set when created), uses [], can store primitives. ArrayList: DYNAMIC size (grows/shrinks), uses add()/remove(), can only store objects (wrapper types). ArrayList requires <code>import java.util.*</code>.' },
        { q: 'What is the correct syntax to declare an array of 10 integers?', a: '<code>int[] array = new int[10];</code> â€” note: <code>array.length</code> (NOT <code>array.length()</code>) gives the size.' },
        { q: 'Which method adds an item to an ArrayList?', a: '<code>add()</code> â€” e.g. <code>list.add("hello");</code>. You can also add at an index: <code>list.add(0, "hello");</code>' },
        { q: 'How do you retrieve a value from a HashMap using a key?', a: '<code>map.get(key)</code> â€” e.g. <code>String val = map.get("name");</code>' },
        { q: 'Which import is needed for ArrayList, Set, and Map?', a: '<code>import java.util.*;</code> â€” This imports the entire java.util package.' },
        { q: 'Java arrays have a length() method â€” True or False?', a: 'FALSE â€” arrays use <code>array.length</code> (property, no parentheses). Strings use <code>str.length()</code> (method, with parentheses). This is a common trick question!' },
        { q: 'Multidimensional arrays are arrays of arrays in Java â€” True or False?', a: 'TRUE â€” a 2D array is an array where each element is itself an array. <code>int[][] matrix = new int[3][4];</code>' },
        { q: 'How do you loop through an array using for-each?', a: '<code>for (int i : array) { }</code> â€” this iterates over each element. The variable type must match the array element type.' }
      ],
      quiz: [
        { q: 'Correct syntax to declare an array of 10 integers:', opts: ['int array = new int(10)', 'int array[] = new int[10]', 'array int[10]', 'new int array[10]'], ans: 1 },
        { q: 'Which method adds an item to an ArrayList?', opts: ['add()', 'insert()', 'append()', 'put()'], ans: 0 },
        { q: 'How do you retrieve a value from a HashMap?', opts: ['map.find(key)', 'map.search(key)', 'map.get(key)', 'map.lookup(key)'], ans: 2 },
        { q: 'Which import is needed for ArrayList, Set, and Map?', opts: ['java.util.*', 'java.data.*', 'java.array.*', 'java.list.*'], ans: 0 },
        { q: 'Java arrays have a length() method â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'Multidimensional arrays are arrays of arrays in Java â€” True or False?', opts: ['True', 'False'], ans: 0 },
        { q: 'How do you declare an ArrayList of Strings?', opts: ['ArrayList<String> list = new ArrayList<>()', 'String[] list = new ArrayList()', 'ArrayList list = new ArrayList<String>()', 'list = new ArrayList<String>()'], ans: 0 },
        { q: 'marks[3][2] refers to:', opts: ['Row 2, Column 3', 'Row 3, Column 2', 'Index 3', 'Invalid syntax'], ans: 1 },
        { q: 'How to loop using for-each in Java?', opts: ['for(i: array)', 'foreach(i in array)', 'for(int i : array)', 'loop(i, array)'], ans: 2 },
        { q: 'A Set automatically maintains sorted order â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'A Map allows multiple identical keys â€” True or False?', opts: ['True', 'False'], ans: 1 },
      ]
    },
    {
      id: 'oop',
      name: 'Classes, Objects & OOP Principles',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Q76â€“90 MCQ 2025. Q1â€“16 in 2024 paper. Section B Q1â€“4. OOP is tested every year.',
      questions: [
        { q: 'What is a constructor? When is it called?', a: 'A constructor is a special method used to INITIALIZE an object. It has the same name as the class and NO return type. It is called automatically when an object is created with the <code>new</code> keyword.' },
        { q: 'What is encapsulation?', a: 'Encapsulation is the process of HIDING internal details (making fields private) and providing access through public getter/setter methods. It protects the data.' },
        { q: 'What is inheritance in Java?', a: 'Inheritance is when one class acquires all the properties and behaviours of a parent class. It uses the <code>extends</code> keyword. E.g. <code>class Dog extends Animal {}</code>' },
        { q: 'What is polymorphism?', a: 'Polymorphism means "many forms". In Java: Method Overloading (same name, different parameters â€” compile time) and Method Overriding (subclass redefines parent method â€” runtime).' },
        { q: 'What is abstraction?', a: 'Abstraction is focusing on IMPORTANT characteristics while hiding the implementation details. Achieved through abstract classes and interfaces.' },
        { q: 'If no constructor is defined, Java provides a:', a: 'Default constructor â€” a no-argument constructor that Java provides automatically if you do not define any constructor.' },
        { q: 'What does the this keyword refer to?', a: 'this refers to the CURRENT object instance. It is used to distinguish instance variables from parameters with the same name.' },
        { q: 'Can you have more than one constructor?', a: 'YES â€” This is called constructor OVERLOADING. Each constructor must have a different parameter list (different types or number of parameters).' },
        { q: 'Which access modifier allows access from anywhere?', a: 'public â€” accessible from any class. private = same class only. protected = same package + subclasses. default (no modifier) = same package only.' },
        { q: 'What is method overloading vs method overriding?', a: 'Overloading: SAME CLASS, same method name but different parameters (multiple methods coexist). Overriding: SUBCLASS has same method name AND parameters as parent â€” redefines the parent behaviour.' }
      ],
      quiz: [
        { q: 'A constructor is used to destroy objects â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'If no constructor is defined, Java provides a:', opts: ['copy constructor', 'default constructor', 'parameterized constructor', 'static constructor'], ans: 1 },
        { q: 'What is the purpose of the this keyword?', opts: ['Access static members', 'Access superclass members', 'Refer to the current object', 'Refer to null object'], ans: 2 },
        { q: 'Which access modifier allows access from anywhere?', opts: ['protected', 'private', 'default', 'public'], ans: 3 },
        { q: 'When one class acquires all properties of a parent class, it is known as:', opts: ['Polymorphism', 'Inheritance', 'Property Acquiring', 'Abstraction'], ans: 1 },
        { q: 'Which keyword is used to inherit a class in Java?', opts: ['inherits', 'extends', 'implements', 'super'], ans: 1 },
        { q: 'If a class has multiple methods with same name but different parameters:', opts: ['Method Duplication', 'Method Overloading', 'Method Overriding', 'Method Multiplication'], ans: 1 },
        { q: 'If subclass has same method as declared in parent class:', opts: ['Method Duplication', 'Method Overloading', 'Method Overriding', 'Method Multiplication'], ans: 2 },
        { q: 'Static methods can access non-static variables directly â€” True or False?', opts: ['True', 'False'], ans: 1 },
        { q: 'The process of hiding internal details is called:', opts: ['Polymorphism', 'Inheritance', 'Encapsulation', 'Abstraction'], ans: 2 },
        { q: 'Which keyword is used to create an interface?', opts: ['interface', 'implements', 'class', 'abstract'], ans: 0 },
        { q: 'Which keyword prevents a method from being overridden?', opts: ['static', 'final', 'protected', 'private'], ans: 1 },
      ]
    },
    {
      id: 'variables',
      name: 'Variable Scope & Types',
      heat: 'warm', heatLabel: 'Likely',
      why: 'Q19,23,27,37â€“39 in 2024 paper. Local vs instance vs static variables.',
      questions: [
        { q: 'What is a local variable?', a: 'A local variable is declared INSIDE a method. It is only accessible within that method and has no default value (must be initialized before use).' },
        { q: 'What is an instance variable?', a: 'An instance variable is declared inside a class but OUTSIDE any method. It belongs to the object (instance) and gets default values (int=0, boolean=false, etc.).' },
        { q: 'What is a static variable?', a: 'A static variable belongs to the CLASS, not to individual objects. All objects share the same static variable. Declared with the <code>static</code> keyword.' },
        { q: 'Which variables are created when an object is created with new?', a: 'Instance variables â€” created when an object is created and destroyed when the object is destroyed.' }
      ],
      quiz: [
        { q: 'A variable declared inside a method is called a:', opts: ['Instance variable', 'Static variable', 'Class variable', 'Local variable'], ans: 3 },
        { q: 'Variables declared with the static keyword belong to:', opts: ['The method', 'The object', 'The class', 'The interface'], ans: 2 },
        { q: 'Which variables are created when an object is created with new?', opts: ['Local variables', 'Instance variables', 'Class variables', 'Static variables'], ans: 1 },
      ]
    },
    {
      id: 'casting',
      name: 'Type Casting & Conversion',
      heat: 'warm', heatLabel: 'Likely',
      why: 'Q24 MCQ. Long answer Q27 (widening vs narrowing). 2025 paper.',
      questions: [
        { q: 'Define casting. What is widening vs narrowing?', a: 'Casting = converting one data type to another. Widening (e.g. intâ†’double): AUTOMATIC, no data loss, smaller to larger type. Narrowing (e.g. doubleâ†’int): must be EXPLICIT e.g. <code>(int)3.9</code>, can lose data (truncates decimal).' },
        { q: 'Java converts int to double using:', a: 'Widening conversion â€” automatic, no cast needed. <code>int x = 5; double y = x;</code> works automatically.' },
        { q: 'Modulus operator (%) can be applied to which types?', a: 'BOTH integers AND floating-point numbers. <code>10 % 3 = 1</code> and <code>10.5 % 3 = 1.5</code>.' }
      ],
      quiz: [
        { q: 'Java converts int to double using:', opts: ['Explicit casting', 'Widening conversion', 'Narrowing conversion', 'Bit shifting'], ans: 1 },
        { q: 'What does (int)3.9 return?', opts: ['4', '3', '3.9', 'Error'], ans: 1 },
        { q: 'What is the output of 10 % 3?', opts: ['1', '3', '10', '0'], ans: 0 },
        { q: 'Modulus (%) can be applied to:', opts: ['Integers only', 'Floating-point only', 'Both A and B', 'Neither'], ans: 2 },
      ]
    },
    {
      id: 'logical_ops',
      name: 'Logic, Boolean & Bitwise Operators',
      heat: 'hot', heatLabel: 'Very likely',
      why: 'Section B Q6 & Q7 (complex boolean expressions) â€” 2 marks easy to pick up.',
      questions: [
        { q: 'Given x=89, what is the output of:\n((x<=49) ^ (x>=30)) ^ (x<99) && ((x>=20)||(x>=45))', a: 'Step by step with x=89:\nâ€¢ (x<=49) = false, (x>=30) = true â†’ false^true = true\nâ€¢ (x<99) = true, (x>=20) = true, (x>=45) = true â†’ (true||true) = true â†’ true&&true = true\nâ€¢ true ^ true = FALSE\nAnswer: false' },
        { q: 'Given x=89, what is the output of:\n((x<=49) & (x>=30)) ^ (x<99) && ((x>=20)||(x>=45))', a: 'Step by step with x=89:\nâ€¢ (x<=49) = false, (x>=30) = true â†’ false & true = false (& not ^)\nâ€¢ (x<99) = true, (x>=20)=true â†’ true&&true = true\nâ€¢ false ^ true = TRUE\nAnswer: true' },
        { q: 'What is the difference between & and && in Java?', a: '& (bitwise AND): evaluates BOTH sides always. && (logical AND): SHORT-CIRCUIT â€” if the left side is false, the right side is NOT evaluated. Same difference for | vs ||.' },
        { q: 'What does ! (NOT) operator do?', a: '! negates a boolean. !true = false, !false = true. The expression !(true && false) = !(false) = true.' }
      ],
      quiz: [
        { q: 'What is the result of true ^ false? (XOR)', opts: ['true', 'false', 'Error', 'null'], ans: 0 },
        { q: 'The expression !(true && false) evaluates to:', opts: ['true', 'false', 'Error', 'null'], ans: 0 },
        { q: '&& vs &: which one short-circuits?', opts: ['&', '&&', 'Both', 'Neither'], ans: 1 },
        { q: 'What operator is used for logical AND in Java?', opts: ['&', '|', '&&', '^^'], ans: 2 },
      ]
    }
  ],

  pastExams: [
    {
      year: 'April 2025 â€” CE 200 (Section A)',
      questions: [
        { q: 'What is the main method signature in Java?', opts: ['public void main(String[] args)', 'public static void main(String[] args)', 'private static void main(String[] args)', 'public static void Main(String[] args)'], ans: 1, exp: 'The main method must be public, static, void, named exactly main (lowercase), and take String[] args.' },
        { q: 'What will be the output of System.out.println(5 + "5");', opts: ['10', '55', '5+5', 'Compilation error'], ans: 1, exp: 'When int is added to String, the int is converted to String and concatenated. 5 + "5" = "55".' },
        { q: 'Which of the following data types can store decimal values?', opts: ['int', 'char', 'boolean', 'double'], ans: 3, exp: 'double and float store decimal values. int, char, boolean do not.' },
        { q: 'Which loop is best suited for running a block of code a KNOWN number of times?', opts: ['while', 'do-while', 'for', 'switch'], ans: 2, exp: 'The for loop is designed for a known count: for(init; condition; update).' },
        { q: 'int a=5; int b=2; System.out.println(a/b); â€” output?', opts: ['2.5', '2', '2.0', 'Compilation error'], ans: 1, exp: 'Integer division in Java truncates the decimal. 5/2 = 2 (not 2.5). To get 2.5, one must be a double.' },
        { q: 'What is the correct way to declare an array in Java?', opts: ['int arr = new int[5]', 'int[] arr = new int[5]', 'int arr = [5]', 'array<int> arr = new array<int>[5]'], ans: 1, exp: 'int[] arr = new int[5]; is the correct declaration.' },
        { q: 'How do you create a constant variable in Java?', opts: ['static int x=10', 'final int x=10', 'const int x=10', 'define x=10'], ans: 1, exp: 'final keyword creates a constant. const is not a Java keyword.' },
        { q: 'What will System.out.println(3==3.0); output?', opts: ['true', 'false', 'Compilation error', 'NaN'], ans: 0, exp: 'Java promotes int 3 to double 3.0, then compares 3.0 == 3.0 which is true.' },
        { q: 'What happens if break is omitted in a switch statement?', opts: ['Compilation error', 'Runtime error', 'Fall-through occurs', 'Program exits'], ans: 2, exp: 'Fall-through: execution continues into the next case. This is often a bug but is intentional in some cases.' },
        { q: 'Given i=1; int j=--i; causes i and j to be:', opts: ['i=0, j=1', 'i=1, j=0', 'i=1, j=1', 'i=0, j=0'], ans: 3, exp: '--i is pre-decrement: decrements i first (i=0), then assigns to j (j=0).' },
        { q: 'String s1="Hello"; String s2="Hello,"; System.out.println(s1==s2); â€” output?', opts: ['true', 'false', 'Compilation error', 'null'], ans: 1, exp: '== on Strings checks if they are the SAME OBJECT, not same content. Different string literals are different objects. Use .equals() for content comparison.' },
        { q: 'Which of the following is NOT a Java keyword?', opts: ['class', 'static', 'void', 'new', 'define'], ans: 4, exp: 'define is NOT a Java keyword. class, static, void, new are all valid Java keywords.' },
      ]
    },
    {
      year: 'April 2025 â€” CE/IS II (Section A, Q1â€“30)',
      questions: [
        { q: 'Java applications require the JDK to be installed on a system â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” Java applications only require the JRE (Java Runtime Environment) to run. The JDK is only needed for development (compiling).' },
        { q: 'An interpreter translates the entire source code before execution â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” A COMPILER translates all at once. An interpreter translates and executes ONE LINE AT A TIME.' },
        { q: 'A compiler reads one line of code at a time â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” That is the interpreter. A compiler reads the ENTIRE program and translates it all at once.' },
        { q: 'The command java -version checks the compiler version â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” java -version checks the JRE version. Use javac -version for the compiler.' },
        { q: 'Which tool is used to compile Java source code?', opts: ['javac', 'java', 'javadoc', 'jar'], ans: 0, exp: 'javac is the Java compiler. java is used to run bytecode. javadoc generates documentation.' },
        { q: 'What is required after installing JDK?', opts: ['Restart system', 'Configure Java Path', 'Format drive', 'Update BIOS'], ans: 1, exp: 'You must set the PATH environment variable so the system can find javac and java commands.' },
        { q: 'A char variable can store multiple characters â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” char stores exactly ONE character, using single quotes: char ch = \'A\';' },
        { q: 'Java supports only post-increment operators â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” Java supports BOTH pre-increment (++x) and post-increment (x++).' },
        { q: 'The ++ operator increases a variable\'s value by 2 â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” ++ increases by 1. To increase by 2, use x += 2.' },
        { q: 'Which is a valid variable declaration?', opts: ['int= score;', 'int score = 90;', 'Score int: 90;', 'int score == 90;'], ans: 1, exp: 'int score = 90; is correct. Type comes first, then name, then = for assignment.' },
        { q: 'The result of 5 + 3 * 2 in Java is:', opts: ['16', '11', '13', '10'], ans: 1, exp: 'Multiplication has higher precedence: 3*2=6, then 5+6=11.' },
        { q: 'What is the result of (double)5 / 2?', opts: ['2', '2.5', '2.0', '3'], ans: 1, exp: '(double)5 casts 5 to 5.0, so 5.0/2 = 2.5.' },
        { q: 'Comparing strings using == checks for content equality â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” == checks object reference (memory location). Use .equals() for content comparison.' },
        { q: 'Math.random() returns a random integer â€” True or False?', opts: ['True', 'False'], ans: 1, exp: 'FALSE â€” Math.random() returns a double between 0.0 (inclusive) and 1.0 (exclusive).' },
      ]
    },
    {
      year: 'April 2024 â€” CE II (Section A)',
      questions: [
        { q: 'When one object acquires all the properties and behaviours of a parent object, it is known as:', opts: ['Polymorphism', 'Inheritance', 'Property Acquiring', 'Abstraction'], ans: 1, exp: 'This is Inheritance â€” child class acquires fields and methods of parent class.' },
        { q: 'Java is a _______ language', opts: ['Weakly typed', 'Strongly typed', 'Moderate typed', 'None of these'], ans: 1, exp: 'Java is strongly typed â€” all variables must have a declared type.' },
        { q: 'Java language was initially called:', opts: ['Sumatra', 'J++', 'Oak', 'Pine'], ans: 2, exp: 'Java was originally named Oak by James Gosling.' },
        { q: 'The new keyword is used to allocate memory at:', opts: ['Code time', 'Compile time', 'Runtime', 'Processing time'], ans: 2, exp: 'new allocates memory at runtime (when the program is running).' },
        { q: 'Who is known as the father of Java?', opts: ['James Gosling', 'M.P Java', 'Charles Babbage', 'Blaise Pascal'], ans: 0, exp: 'James Gosling created Java at Sun Microsystems in the early 1990s.' },
        { q: 'If a class has multiple methods having same name but different parameters:', opts: ['Method Duplication', 'Method Overloading', 'Method Overriding', 'Method Multiplication'], ans: 1, exp: 'This is Method Overloading â€” same method name, different parameter lists.' },
        { q: 'Assuming + and * are arithmetic operators, what does 2 + 4 * 5 + 1 evaluate to?', opts: ['36', '31', '26', '23'], ans: 1, exp: 'Operator precedence: 4*5=20 first, then 2+20+1=23. Wait â€” let me recalculate: 2 + 4*5 + 1 = 2 + 20 + 1 = 23. But answer is 23 (D).' },
        { q: 'A package is a collection of:', opts: ['Classes', 'Interfaces', 'Editing tools', 'Classes and interfaces'], ans: 3, exp: 'A package is a collection of both classes and interfaces (and sub-packages).' },
        { q: 'If subclass has the same method as in the parent class, it is known as:', opts: ['Method Duplication', 'Method Overloading', 'Method Overriding', 'Method Multiplication'], ans: 2, exp: 'Method Overriding â€” subclass provides its own implementation of a method defined in the parent.' },
      ]
    }
  ],

  sectionC: [
    {
      id: 'sc1',
      q: 'Mary, a novice programmer, wants to store the names and marks of 3 students in a multidimensional array. She wrote the code below â€” it has many errors. (a) Identify and correct all errors [3 marks]. (b) Write a for-loop to print only the marks of each student [2 marks].',
      marks: '5 marks',
      errorCode: `public class storeStdMarks {
  public static void main (String[] Exams) {
    String dimArray [] = new Int [3][2];   // â† Multiple errors
    dimArray = [0][0] = John Annan;
    dimArray = [0][1] = 86;
    dimArray = [1][2] = Theresa Opoku;
    dimArray = [1][3] = 83;
    dimArray = [1][4] = Titus Clinton;
    dimArray = [1][5] = 79;
  }
}`,
      subQuestions: [
        {
          label: 'a) Errors and corrections:',
          hint: `Errors:
1. String dimArray[][] = new Int[3][2]; â†’ Should be: Object[][] dimArray = new Object[3][2]; (Int is wrong, type should be Object to store both String and int)
2. dimArray = [0][0] = John Annan; â†’ Should be: dimArray[0][0] = "John Annan"; (no = before [, string needs quotes)
3. Row indices are wrong â€” student 1 is row 0, student 2 should be row 1, student 3 should be row 2
4. Column indices go out of bounds â€” 2D array has 2 columns (0 and 1)

Corrected code:
Object[][] dimArray = new Object[3][2];
dimArray[0][0] = "John Annan";
dimArray[0][1] = 86;
dimArray[1][0] = "Theresa Opoku";
dimArray[1][1] = 83;
dimArray[2][0] = "Titus Clinton";
dimArray[2][1] = 79;`
        },
        {
          label: 'b) For-loop to print marks:',
          hint: `for (int i = 0; i < dimArray.length; i++) {
    System.out.println(dimArray[i][1]);
}
// Output: 86, 83, 79`
        }
      ]
    },
    {
      id: 'sc2',
      q: 'Write a loop that computes the sum of all numbers between 2 and 100 inclusive that are whole number multiples of 5 or 7. [2 marks]',
      marks: '2 marks',
      subQuestions: [{
        label: 'Solution:',
        hint: `int sum = 0;
for (int i = 2; i <= 100; i++) {
    if (i % 5 == 0 || i % 7 == 0) {
        sum += i;
    }
}
System.out.println("Sum = " + sum);
// Sum = 1630`
      }]
    },
    {
      id: 'sc3',
      q: 'Write a conditional statement with three branches that sets y to: 2 if x is positive, -3 if x is negative, and 0 if x is zero. [3 marks]',
      marks: '3 marks',
      subQuestions: [{
        label: 'Solution:',
        hint: `int y;
if (x > 0) {
    y = 2;
} else if (x < 0) {
    y = -3;
} else {
    y = 0;
}`
      }]
    },
    {
      id: 'sc4',
      q: 'Write Java code that will display the first 20 positive numbers that are divisible by 5 or 6 but NOT both. [3 marks]',
      marks: '3 marks',
      subQuestions: [{
        label: 'Solution:',
        hint: `int count = 0;
int i = 1;
while (count < 20) {
    boolean div5 = (i % 5 == 0);
    boolean div6 = (i % 6 == 0);
    // XOR: divisible by 5 OR 6 but NOT BOTH
    if (div5 ^ div6) {
        System.out.println(i);
        count++;
    }
    i++;
}`
      }]
    },
    {
      id: 'sc5',
      q: 'Given a two-dimensional Array of doubles: double[][] marks = new double[n][m]; Write Java code to find the average of all numbers in the array. [5 marks]',
      marks: '5 marks',
      subQuestions: [{
        label: 'Solution:',
        hint: `double sum = 0;
int count = 0;
for (int i = 0; i < marks.length; i++) {
    for (int j = 0; j < marks[i].length; j++) {
        sum += marks[i][j];
        count++;
    }
}
double average = sum / count;
System.out.println("Average = " + average);`
      }]
    },
    {
      id: 'sc6',
      q: 'Rewrite the following switch statement into if-else statements. [3 marks]\nswitch(z) {\n  case 4: y -= 2*x^y; break;\n  case 5: y += x^y; break;\n  case 6: y += x + 3%y; break;\n  default: y += x-y;\n}',
      marks: '3 marks',
      subQuestions: [{
        label: 'Solution:',
        hint: `int z = x + 2*y;
if (z == 4) {
    y -= 2*x^y;
} else if (z == 5) {
    y += x^y;
} else if (z == 6) {
    y += x + 3%y;
} else {
    y += x - y;
}
// Note: ^ in Java is XOR (not exponent). Use Math.pow() for exponents.`
      }]
    },
    {
      id: 'sc7',
      q: 'Write a Java program that uses a class called Student with fields: name (String), indexNumber (String), and marks (double[]). Include a constructor, a method to calculate average marks, and a method to print the student's details. [5 marks] (Likely Section C based on OOP topics)',
      marks: '5 marks (predicted)',
      subQuestions: [{
        label: 'Sample solution:',
        hint: `public class Student {
    String name;
    String indexNumber;
    double[] marks;

    // Constructor
    public Student(String name, String indexNumber, double[] marks) {
        this.name = name;
        this.indexNumber = indexNumber;
        this.marks = marks;
    }

    // Method to calculate average
    public double getAverage() {
        double sum = 0;
        for (double m : marks) {
            sum += m;
        }
        return sum / marks.length;
    }

    // Method to print details
    public void printDetails() {
        System.out.println("Name: " + name);
        System.out.println("Index: " + indexNumber);
        System.out.println("Average: " + getAverage());
    }

    public static void main(String[] args) {
        double[] m = {75, 82, 90, 68};
        Student s = new Student("Kwame Asante", "CE/200/21", m);
        s.printDetails();
    }
}`
      }]
    },
    {
      id: 'sc8',
      q: 'Write a Java program using exception handling that reads an integer from the user. If the user enters a non-integer, catch the exception and display an error message. Use a finally block to close the scanner. [4 marks] (Predicted based on past exam patterns)',
      marks: '4 marks (predicted)',
      subQuestions: [{
        label: 'Solution:',
        hint: `import java.util.Scanner;
import java.util.InputMismatchException;

public class SafeInput {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        try {
            System.out.print("Enter an integer: ");
            int num = sc.nextInt();
            System.out.println("You entered: " + num);
        } catch (InputMismatchException e) {
            System.out.println("Error: Please enter a valid integer.");
        } finally {
            sc.close(); // Always runs
            System.out.println("Scanner closed.");
        }
    }
}`
      }]
    },
    {
      id: 'sc9',
      q: 'Write a Java method called isPrime that takes an integer n and returns true if it is prime, false otherwise. Then write a loop in main to print all prime numbers between 1 and 50. [4 marks] (Predicted â€” method writing + loops)',
      marks: '4 marks (predicted)',
      subQuestions: [{
        label: 'Solution:',
        hint: `public class PrimeChecker {

    public static boolean isPrime(int n) {
        if (n < 2) return false;
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) return false;
        }
        return true;
    }

    public static void main(String[] args) {
        for (int i = 1; i <= 50; i++) {
            if (isPrime(i)) {
                System.out.print(i + " ");
            }
        }
        // Output: 2 3 5 7 11 13 17 19 23 29 31 37 41 43 47
    }
}`
      }]
    },
    {
      id: 'sc10',
      q: 'John has declared: integer maxValue == Maths.max(20, 15, 50); â€” without changing the variable name, rewrite the correct code. [1 mark]',
      marks: '1 mark',
      subQuestions: [{
        label: 'Corrected code:',
        hint: `int maxValue = Math.max(20, Math.max(15, 50));
// OR more clearly:
int maxValue = Math.max(Math.max(20, 15), 50);
// Result: maxValue = 50
// Errors fixed: 'integer'â†’'int', '=='â†’'=', 'Maths'â†’'Math', Math.max only takes 2 args (nested calls needed)`
      }]
    },
    {
      id: 'sc11',
      q: 'Given two sets A and B in Java: (a) Write code to find their intersection stored in B. (b) Write code to subtract B from A. (c) Write code to find their union. [3 marks]',
      marks: '3 marks',
      subQuestions: [{
        label: 'Solutions:',
        hint: `// Assume A and B are HashSet<Integer>
import java.util.*;

// (a) Intersection â€” stored in B
B.retainAll(A);  // B now contains only elements in both A and B

// (b) Subtract B from A (A minus B)
A.removeAll(B);  // A now contains elements in A but not in B

// (c) Union of A and B
A.addAll(B);     // A now contains all elements from both A and B`
      }]
    },
    {
      id: 'sc12',
      q: 'Write a Java program that reads 5 integers from the user, stores them in an array, then finds and prints the maximum and minimum values. [3 marks] (Predicted)',
      marks: '3 marks (predicted)',
      subQuestions: [{
        label: 'Solution:',
        hint: `import java.util.Scanner;

public class MaxMin {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int[] nums = new int[5];

        for (int i = 0; i < 5; i++) {
            System.out.print("Enter number " + (i+1) + ": ");
            nums[i] = sc.nextInt();
        }

        int max = nums[0], min = nums[0];
        for (int i = 1; i < nums.length; i++) {
            if (nums[i] > max) max = nums[i];
            if (nums[i] < min) min = nums[i];
        }

        System.out.println("Maximum: " + max);
        System.out.println("Minimum: " + min);
        sc.close();
    }
}`
      }]
    },
    {
      id: 'sc13',
      q: 'Write a Java program to reverse a String without using any built-in reverse method. [3 marks] (Predicted based on String methods topic)',
      marks: '3 marks (predicted)',
      subQuestions: [{
        label: 'Solution:',
        hint: `public class ReverseString {
    public static void main(String[] args) {
        String original = "Hello UMAT";
        String reversed = "";

        for (int i = original.length() - 1; i >= 0; i--) {
            reversed += original.charAt(i);
        }

        System.out.println("Original: " + original);
        System.out.println("Reversed: " + reversed);
        // Output: Reversed: TAMU olleH
    }
}`
      }]
    },
    {
      id: 'sc14',
      q: 'Write Java code to read integers from the user until they enter -1 (sentinel value). Then print the count and sum of all entered numbers. [3 marks] (Predicted â€” while loops with sentinel)',
      marks: '3 marks (predicted)',
      subQuestions: [{
        label: 'Solution:',
        hint: `import java.util.Scanner;

public class Sentinel {
    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int sum = 0, count = 0;

        System.out.print("Enter a number (-1 to stop): ");
        int num = sc.nextInt();

        while (num != -1) {
            sum += num;
            count++;
            System.out.print("Enter a number (-1 to stop): ");
            num = sc.nextInt();
        }

        System.out.println("Count: " + count);
        System.out.println("Sum: " + sum);
        sc.close();
    }
}`
      }]
    },
    {
      id: 'sc15',
      q: 'Define a class called Rectangle with fields width and height. Add methods to calculate area (width Ã— height) and perimeter (2 Ã— (width + height)). Create two Rectangle objects and print their area and perimeter. [4 marks] (Predicted â€” OOP/class writing)',
      marks: '4 marks (predicted)',
      subQuestions: [{
        label: 'Solution:',
        hint: `public class Rectangle {
    double width;
    double height;

    // Constructor
    public Rectangle(double width, double height) {
        this.width = width;
        this.height = height;
    }

    public double area() {
        return width * height;
    }

    public double perimeter() {
        return 2 * (width + height);
    }

    public static void main(String[] args) {
        Rectangle r1 = new Rectangle(5, 3);
        Rectangle r2 = new Rectangle(10, 7);

        System.out.println("R1 Area: " + r1.area());
        System.out.println("R1 Perimeter: " + r1.perimeter());
        System.out.println("R2 Area: " + r2.area());
        System.out.println("R2 Perimeter: " + r2.perimeter());
    }
}`
      }]
    }
  ],

  fillBlanks: [
    { q: 'An ___ is created from a class.', a: 'object' },
    { q: 'The ___ constructor takes no arguments.', a: 'default' },
    { q: "The object's data is usually made private and accessed via ___ methods.", a: 'getter/setter' },
    { q: 'The process of hiding internal details is called ___.', a: 'encapsulation' },
    { q: 'Arrays.sort() is used to sort an array in ___ order.', a: 'ascending (natural/increasing)' },
    { q: 'A file that does not exist will throw a ___ exception when opened for reading.', a: 'FileNotFoundException' },
    { q: 'The method output.close() is used to ___ the file after writing.', a: 'close / flush' },
    { q: 'The base class for all exceptions in Java is ___.', a: 'Throwable' },
    { q: 'The output of (int)(Math.random()*10) ranges from ___ to ___.', a: '0 to 9' },
    { q: 'Casting a double to int will ___ the decimal part.', a: 'truncate (remove)' },
    { q: 'A variable declared without a value is said to be ___.', a: 'uninitialized' },
    { q: 'int x = 2; x *= 3; will make x equal to ___.', a: '6' },
    { q: 'Assembly language uses ___ to represent instructions.', a: 'mnemonics' },
    { q: 'To check Java version, we use the command ___.', a: 'java -version' },
    { q: 'The acronym JDK stands for ___.', a: 'Java Development Kit' },
    { q: 'The ___ translates high-level code into machine code all at once.', a: 'compiler' },
    { q: 'Variables declared in a method are called ___ variables.', a: 'local' },
    { q: 'The escape sequence for a tab character is ___.', a: '\\t' },
    { q: 'The for loop contains three parts: initialization, ___, and update.', a: 'condition' },
    { q: 'To handle input type errors from Scanner, you catch the ___ exception.', a: 'InputMismatchException' },
    { q: 'The try block contains the ___ block, used when an exception must be handled.', a: 'try' },
    { q: 'Java language was initially called ___.', a: 'Oak' },
    { q: 'The ___ method of String removes leading and trailing whitespace.', a: 'trim()' },
    { q: 'To convert a String "99" to an integer, use ___.', a: 'Integer.parseInt("99")' },
    { q: 'A ___ is a collection of classes and interfaces in Java.', a: 'package' },
    { q: 'The finally block in exception handling ___ executes.', a: 'always (whether exception occurs or not)' },
    { q: '++ is the ___ operator in Java.', a: 'increment' },
    { q: 'To declare an ArrayList of Strings: ArrayList<___> list = new ArrayList<>();', a: 'String' },
    { q: 'Math.floor(3.9) returns ___.', a: '3.0' },
    { q: 'The ___ keyword in Java is used to prevent a method from being overridden.', a: 'final' }
  ],

  cheatsheet: [
    {
      title: 'JDK / JRE / JVM',
      icon: 'â˜•',
      items: [
        'JDK = Java Development Kit (for developers)',
        'JRE = Java Runtime Environment (to run programs)',
        'JVM = Java Virtual Machine (executes bytecode)',
        '<code>javac</code> = compiler tool | <code>java</code> = run tool',
        'Compiler = all at once | Interpreter = line by line',
        'Bytecode = output of javac (platform-independent)'
      ]
    },
    {
      title: 'Primitive data types',
      icon: 'ðŸ“¦',
      items: [
        '<code>int, double, float, long, byte, short</code>',
        '<code>char</code> (single quotes: \'A\')',
        '<code>boolean</code> (true / false)',
        'String is NOT primitive â€” it is an object',
        'int default: 0 | boolean default: false',
        'double default: 0.0 | object default: null'
      ]
    },
    {
      title: 'Operator Precedence',
      icon: 'ðŸ”¢',
      items: [
        '1st: <code>()</code> parentheses',
        '2nd: <code>*, /, %</code> (multiply/divide/modulo)',
        '3rd: <code>+, -</code> (add/subtract)',
        '5 + 3 * 2 = <strong>11</strong> (NOT 16)',
        '<code>++</code> increases by 1, <code>**</code> is NOT valid in Java',
        '<code>^</code> in Java is XOR, NOT exponent!'
      ]
    },
    {
      title: 'Scanner Usage',
      icon: 'âŒ¨ï¸',
      items: [
        '<code>import java.util.Scanner;</code>',
        '<code>Scanner sc = new Scanner(System.in);</code>',
        '<code>sc.nextInt()</code> â€” reads integer',
        '<code>sc.nextDouble()</code> â€” reads double',
        '<code>sc.next()</code> â€” reads one word',
        '<code>sc.nextLine()</code> â€” reads full line',
        '<code>sc.close()</code> â€” closes stream'
      ]
    },
    {
      title: 'Math class methods',
      icon: 'ðŸ“',
      items: [
        '<code>Math.random()</code> â†’ double 0.0 to &lt;1.0',
        '<code>Math.floor(3.8)</code> â†’ 3.0 (round down)',
        '<code>Math.ceil(3.2)</code> â†’ 4.0 (round up)',
        '<code>Math.round(3.5)</code> â†’ 4 (nearest)',
        '<code>Math.abs(-5)</code> â†’ 5 (absolute value)',
        '<code>Math.max(a, b)</code> â†’ larger of two values',
        'java.lang.Math is auto-imported (no import needed)'
      ]
    },
    {
      title: 'String methods',
      icon: 'ðŸ“',
      items: [
        '<code>s.length()</code> â€” length of string',
        '<code>s.charAt(0)</code> â€” char at index 0 (0-based!)',
        '<code>s.substring(1, 3)</code> â€” chars at index 1,2',
        '<code>s.toUpperCase()</code> / <code>toLowerCase()</code>',
        '<code>s.trim()</code> â€” remove leading/trailing spaces',
        '<code>s.equals("x")</code> â€” compare content (NOT ==)',
        '<code>s.contains("x")</code> â€” check if substring exists'
      ]
    },
    {
      title: 'Exception Handling',
      icon: 'âš ï¸',
      items: [
        '<code>Throwable</code> â†’ root of all exceptions',
        '<code>try { } catch(Exception e) { } finally { }</code>',
        '<code>finally</code> ALWAYS runs (with or without exception)',
        '<code>InputMismatchException</code> â€” wrong input type',
        '<code>FileNotFoundException</code> â€” file not found',
        '<code>ArithmeticException</code> â€” e.g. int/0',
        '3.0 / 0 = <code>Infinity</code> (floating point, not error)'
      ]
    },
    {
      title: 'Arrays & ArrayList',
      icon: 'ðŸ“‹',
      items: [
        '<code>int[] arr = new int[5];</code> // fixed size',
        '<code>arr[0] = 10;</code> // access by index',
        '<code>arr.length</code> // NOT arr.length()',
        '<code>ArrayList&lt;String&gt; list = new ArrayList&lt;&gt;();</code>',
        '<code>list.add("x");</code> <code>list.remove(0);</code>',
        '<code>list.get(0);</code> <code>list.size();</code>',
        '<code>import java.util.*;</code>'
      ]
    },
    {
      title: 'OOP Concepts',
      icon: 'ðŸ—ï¸',
      items: [
        'Constructor: same name as class, no return type',
        'Called automatically when object is created with <code>new</code>',
        'Default constructor: no arguments (auto-provided)',
        '<code>this</code> = refers to current object',
        'Encapsulation = private fields + getters/setters',
        '<code>public</code> = anywhere | <code>private</code> = same class only',
        '<code>extends</code> = inheritance | <code>implements</code> = interface'
      ]
    },
    {
      title: 'Casting & Conversion',
      icon: 'ðŸ”„',
      items: [
        'Widening: intâ†’double (automatic, no data loss)',
        'Narrowing: doubleâ†’int (explicit: <code>(int)3.9</code> = 3)',
        'Truncates decimal â€” does NOT round',
        '<code>Integer.parseInt("5")</code> â†’ int 5',
        '<code>String.valueOf(5)</code> â†’ "5"',
        '<code>Integer.toString(5)</code> â†’ "5"'
      ]
    },
    {
      title: 'Common Loops',
      icon: 'ðŸ”',
      items: [
        '<code>for(int i=0; i&lt;n; i++)</code> â€” known count',
        '<code>while(condition)</code> â€” check first, may not run',
        '<code>do { } while(condition)</code> â€” runs at least once',
        '<code>for(int x : array)</code> â€” for-each loop',
        'break = exit loop | continue = skip iteration',
        'do-while always runs at least 1 time!'
      ]
    },
    {
      title: 'Logical & Bitwise Ops',
      icon: 'âš¡',
      items: [
        '<code>&&</code> = AND (short-circuit) | <code>&</code> = AND (no short-circuit)',
        '<code>||</code> = OR (short-circuit) | <code>|</code> = OR (no short-circuit)',
        '<code>!</code> = NOT | <code>^</code> = XOR',
        'XOR true only when DIFFERENT: true^false=true',
        'Short-circuit: false && anything = false (skips right)',
        '<code>==</code> vs <code>=</code>: == is comparison, = is assignment!'
      ]
    }
  ]
};

// ===================================
// PROGRESS TRACKER
// ===================================
let progress = {};

function saveProgress() {
  // stored in-memory (localStorage not available in this environment)
}

function toggleProgress(id) {
  progress[id] = !progress[id];
  saveProgress();
  buildProgressTracker();
}

function buildProgressTracker() {
  const el = document.getElementById('pt-items');
  if (!el) return;
  el.innerHTML = DATA.topics.map(t => `
    <div class="pt-item ${progress[t.id] ? 'done' : ''}" data-toggle-progress="${t.id}">
      <div class="pt-check">${progress[t.id] ? 'âœ“' : ''}</div>
      <div class="pt-label">${t.name.split(' ')[0]} ${t.name.split(' ')[1] || ''}</div>
    </div>
  `).join('');
  const done = DATA.topics.filter(t => progress[t.id]).length;
  const pct = Math.round((done / DATA.topics.length) * 100);
  document.getElementById('pt-fill').style.width = pct + '%';
  document.getElementById('pt-pct').textContent = pct + '%';
}

// ===================================
// PAGE NAV
// ===================================
function showPage(id, btn) {
  document.querySelectorAll('.page').forEach(p => p.classList.remove('active'));
  document.getElementById('page-' + id).classList.add('active');
  document.querySelectorAll('nav button').forEach(b => b.classList.remove('active'));
  if (btn) btn.classList.add('active');
}

// ===================================
// HOME
// ===================================
function buildHome() {
  const el = document.getElementById('home-topics');
  el.innerHTML = DATA.topics.map(t => `
    <div class="topic-card ${t.heat}" data-goto-topic="${t.id}">
      <div class="tc-head">
        <span class="tc-name">${t.name}</span>
        <span class="badge ${t.heat}">${t.heatLabel}</span>
      </div>
      <div class="tc-desc">${t.why}</div>
    </div>
  `).join('');
}

function goToTopic(id) {
  showPage('topics', document.querySelector('nav button[data-page="topics"]'));
  setTimeout(() => {
    const el = document.getElementById('td-' + id);
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' });
      openTopic(id);
    }
  }, 50);
}

// ===================================
// TOPICS
// ===================================
function buildTopics() {
  const el = document.getElementById('topics-list');
  el.innerHTML = DATA.topics.map(t => `
    <div class="topic-detail" id="td-${t.id}">
      <div class="td-header" data-toggle-topic="${t.id}">
        <div class="td-title">
          <span class="chevron" id="chev-${t.id}">â€º</span>
          ${t.name}
          <span class="badge ${t.heat}">${t.heatLabel}</span>
        </div>
        <span style="font-size:11px;color:var(--muted)">${t.questions.length} Q's</span>
      </div>
      <div class="td-body" id="body-${t.id}">
        <div style="font-size:11.5px;color:var(--muted);padding-top:10px;margin-bottom:8px;">ðŸ“Œ ${t.why}</div>
        ${t.questions.map((q, i) => `
          <div class="q-item">
            <div class="q-text">${q.q.replace(/\n/g, '<br>')}</div>
            <button class="ans-btn" data-toggle-ans="ans-${t.id}-${i}">Show answer</button>
            <div class="ans-box" id="ans-${t.id}-${i}">${q.a}</div>
          </div>
        `).join('')}
        <div style="margin-top:12px;">
          <button class="btn-outline" style="font-size:11px;" data-mark-done="${t.id}">
            ${progress[t.id] ? 'âœ“ Marked done' : 'â—‹ Mark as studied'}
          </button>
        </div>
      </div>
    </div>
  `).join('');
}

function markDone(id, btn) {
  progress[id] = !progress[id];
  saveProgress();
  btn.textContent = progress[id] ? 'âœ“ Marked done' : 'â—‹ Mark as studied';
  buildProgressTracker();
}

function toggleTopic(id) {
  const body = document.getElementById('body-' + id);
  const chev = document.getElementById('chev-' + id);
  body.classList.toggle('open');
  chev.classList.toggle('open');
}

function openTopic(id) {
  const body = document.getElementById('body-' + id);
  const chev = document.getElementById('chev-' + id);
  body.classList.add('open');
  chev.classList.add('open');
}

function expandAll() {
  DATA.topics.forEach(t => openTopic(t.id));
}

function collapseAll() {
  DATA.topics.forEach(t => {
    document.getElementById('body-' + t.id).classList.remove('open');
    document.getElementById('chev-' + t.id).classList.remove('open');
  });
}

function filterTopics(val) {
  const v = val.toLowerCase();
  DATA.topics.forEach(t => {
    const card = document.getElementById('td-' + t.id);
    const match = t.name.toLowerCase().includes(v) ||
      t.questions.some(q => q.q.toLowerCase().includes(v) || q.a.toLowerCase().includes(v));
    card.style.display = match ? '' : 'none';
    if (match && v) openTopic(t.id);
  });
}

function toggleAns(id, btn) {
  const el = document.getElementById(id);
  el.classList.toggle('show');
  btn.textContent = el.classList.contains('show') ? 'Hide answer' : 'Show answer';
}

// ===================================
// QUIZ
// ===================================
let quizFilter = 'all';
let quizQs = [], quizIdx = 0, quizScore = 0;
let quizTimerInterval = null, quizSeconds = 0;

function setQuizFilter(f, el) {
  quizFilter = f;
  document.querySelectorAll('.quiz-opt').forEach(b => b.classList.remove('active'));
  el.classList.add('active');
}

function buildQuizSetup() {
  const el = document.getElementById('topic-select');
  el.innerHTML = DATA.topics.map(t => `
    <div class="ts-item selected" id="ts-${t.id}" data-toggle-ts="${t.id}">
      <span class="ts-check" id="tsc-${t.id}">âœ“</span>
      ${t.name}
    </div>
  `).join('');
}

function toggleTopicSelect(id) {
  const el = document.getElementById('ts-' + id);
  const check = document.getElementById('tsc-' + id);
  el.classList.toggle('selected');
  check.textContent = el.classList.contains('selected') ? 'âœ“' : '';
}

function selectAllTopics() {
  DATA.topics.forEach(t => {
    document.getElementById('ts-' + t.id).classList.add('selected');
    document.getElementById('tsc-' + t.id).textContent = 'âœ“';
  });
}

function deselectAllTopics() {
  DATA.topics.forEach(t => {
    document.getElementById('ts-' + t.id).classList.remove('selected');
    document.getElementById('tsc-' + t.id).textContent = '';
  });
}

function startQuiz() {
  const selected = DATA.topics.filter(t => document.getElementById('ts-' + t.id)?.classList.contains('selected'));
  if (!selected.length) { alert('Please select at least one topic!'); return; }
  quizQs = [];
  selected.forEach(t => t.quiz.forEach(q => quizQs.push({ ...q, topicName: t.name, heat: t.heat })));
  if (quizFilter === 'hot') quizQs = quizQs.filter(q => q.heat === 'hot');
  quizQs = quizQs.sort(() => Math.random() - 0.5);
  if (quizQs.length === 0) { alert('No questions found for selected filter!'); return; }
  quizIdx = 0; quizScore = 0; quizSeconds = 0;
  document.getElementById('quiz-setup').classList.add('hidden');
  document.getElementById('quiz-active').classList.add('show');
  document.getElementById('score-card').classList.remove('show');
  document.getElementById('q-card').style.display = '';
  document.querySelector('.q-progress').style.display = '';
  document.getElementById('q-feedback').style.display = '';
  startTimer();
  renderQuestion();
}

function startTimer() {
  clearInterval(quizTimerInterval);
  quizTimerInterval = setInterval(() => {
    quizSeconds++;
    const m = String(Math.floor(quizSeconds / 60)).padStart(2, '0');
    const s = String(quizSeconds % 60).padStart(2, '0');
    document.getElementById('quiz-timer').textContent = m + ':' + s;
  }, 1000);
}

function renderQuestion() {
  const q = quizQs[quizIdx];
  const pct = Math.round((quizIdx / quizQs.length) * 100);
  document.getElementById('prog-fill').style.width = pct + '%';
  document.getElementById('q-counter').textContent = (quizIdx + 1) + ' / ' + quizQs.length;
  document.getElementById('q-topic-tag').textContent = '// ' + q.topicName;
  const mainEl = document.getElementById('q-main');
  if (q.code) {
    mainEl.innerHTML = q.q + '<pre>' + q.code + '</pre>';
  } else {
    mainEl.textContent = q.q;
  }
  document.getElementById('q-feedback').className = 'feedback';
  document.getElementById('q-feedback').textContent = '';
  document.getElementById('next-btn').classList.remove('show');
  const letters = ['A', 'B', 'C', 'D', 'E'];
  const opts = document.getElementById('q-options');
  opts.innerHTML = q.opts.map((o, i) => `
    <button class="opt-btn" data-select-opt="${i}">
      <span class="opt-letter">${letters[i]}</span>${o}
    </button>
  `).join('');
}

function selectOpt(idx) {
  const q = quizQs[quizIdx];
  const btns = document.querySelectorAll('.opt-btn');
  btns.forEach(b => b.disabled = true);
  const fb = document.getElementById('q-feedback');
  if (idx === q.ans) {
    btns[idx].classList.add('correct');
    fb.className = 'feedback correct';
    fb.textContent = 'âœ“ Correct! ' + (q.exp || '');
    quizScore++;
  } else {
    btns[idx].classList.add('wrong');
    btns[q.ans].classList.add('correct');
    fb.className = 'feedback wrong';
    fb.textContent = 'âœ— The correct answer is: ' + q.opts[q.ans] + (q.exp ? ' â€” ' + q.exp : '');
  }
  fb.style.display = '';
  document.getElementById('next-btn').classList.add('show');
}

function nextQuestion() {
  quizIdx++;
  if (quizIdx >= quizQs.length) {
    showScore();
  } else {
    renderQuestion();
  }
}

function showScore() {
  clearInterval(quizTimerInterval);
  document.getElementById('q-card').style.display = 'none';
  document.querySelector('.q-progress').style.display = 'none';
  document.getElementById('q-feedback').style.display = 'none';
  document.getElementById('next-btn').classList.remove('show');
  const pct = Math.round((quizScore / quizQs.length) * 100);
  const sc = document.getElementById('score-card');
  sc.classList.add('show');
  const color = pct >= 70 ? 'var(--green)' : pct >= 50 ? 'var(--yellow)' : 'var(--red)';
  document.getElementById('score-big').style.color = color;
  document.getElementById('score-big').textContent = pct + '%';
  const msgs = pct === 100 ? 'ðŸ† Perfect score! You are ready for the exam!' :
    pct >= 80 ? 'ðŸŽ‰ Excellent! A well-deserved high score.' :
    pct >= 70 ? 'ðŸ‘ Good work! Review the ones you missed.' :
    pct >= 50 ? 'ðŸ“š Keep studying â€” you\'re halfway there!' :
    'ðŸ’ª Don\'t give up! Review the topics and try again.';
  document.getElementById('score-msg').textContent = msgs;
  document.getElementById('sb-correct').textContent = quizScore;
  document.getElementById('sb-wrong').textContent = quizQs.length - quizScore;
  const m = String(Math.floor(quizSeconds / 60)).padStart(2, '0');
  const s = String(quizSeconds % 60).padStart(2, '0');
  document.getElementById('sb-time').textContent = m + ':' + s;
}

function resetQuiz() {
  clearInterval(quizTimerInterval);
  document.getElementById('quiz-setup').classList.remove('hidden');
  document.getElementById('quiz-active').classList.remove('show');
  document.getElementById('q-card').style.display = '';
  document.querySelector('.q-progress').style.display = '';
  document.getElementById('q-feedback').style.display = '';
  document.getElementById('score-card').classList.remove('show');
  document.getElementById('quiz-timer').textContent = '00:00';
}

// ===================================
// PAST EXAMS
// ===================================
function buildPastExams() {
  const el = document.getElementById('past-exams-list');
  el.innerHTML = DATA.pastExams.map((exam, ei) => `
    <div class="exam-year-header">
      <span class="exam-year-badge">${exam.year.split('â€”')[0].trim()}</span>
      <span class="exam-year-title">${exam.year.split('â€”')[1] ? 'â€” ' + exam.year.split('â€”')[1].trim() : ''}</span>
    </div>
    ${exam.questions.map((q, qi) => `
      <div class="exam-q-card">
        <div class="exam-q-header" data-toggle-exam-q="eq-${ei}-${qi}" data-toggle-exam-chev="eqc-${ei}-${qi}">
          <div class="exam-q-text">${qi + 1}. ${q.q}</div>
          <div class="exam-q-meta">
            <span class="badge ${['hot','warm','cool'][qi % 3]}">Q${qi+1}</span>
            <span class="chevron" id="eqc-${ei}-${qi}">â€º</span>
          </div>
        </div>
        <div class="exam-q-body" id="eq-${ei}-${qi}">
          <div style="margin-top:12px;">
            <div style="font-size:12px;color:var(--muted);margin-bottom:8px;">Options:</div>
            ${q.opts.map((o, oi) => `
              <div style="font-size:12.5px;padding:5px 10px;border-radius:6px;margin-bottom:4px;background:${oi === q.ans ? 'var(--green-glow)' : 'var(--surface2)'};border:1px solid ${oi === q.ans ? 'rgba(74,222,128,0.25)' : 'var(--border)'};color:${oi === q.ans ? 'var(--green)' : 'var(--muted)'};">
                ${['A','B','C','D','E'][oi]}. ${o} ${oi === q.ans ? 'âœ“' : ''}
              </div>
            `).join('')}
            ${q.exp ? `<div style="margin-top:10px;background:var(--surface2);border-left:3px solid var(--accent);padding:8px 12px;border-radius:0 6px 6px 0;font-size:12px;color:var(--muted);">ðŸ’¡ ${q.exp}</div>` : ''}
          </div>
        </div>
      </div>
    `).join('')}
  `).join('');
}

function toggleExamQ(bodyId, chevId) {
  const body = document.getElementById(bodyId);
  const chev = document.getElementById(chevId);
  body.classList.toggle('open');
  chev.classList.toggle('open');
}

// ===================================
// SECTION C
// ===================================
function buildSectionC() {
  const el = document.getElementById('section-c-list');
  el.innerHTML = DATA.sectionC.map((item, i) => `
    <div class="sec-c-card">
      <div class="sc-header" data-toggle-sc="sc-${i}" data-toggle-sc-chev="scc-${i}">
        <div class="sc-left">
          <div class="sc-q">${i + 1}. ${item.q.replace(/\n/g, '<br>')}</div>
        </div>
        <div style="display:flex;flex-direction:column;align-items:flex-end;gap:6px;flex-shrink:0;">
          <div class="sc-marks">[${item.marks}]</div>
          <span class="chevron" id="scc-${i}">â€º</span>
        </div>
      </div>
      <div class="sc-body" id="sc-${i}">
        ${item.errorCode ? `<div class="code-block">${escapeHtml(item.errorCode)}</div>` : ''}
        ${item.subQuestions.map((sq, sqi) => `
          <div class="sc-subq">
            <div class="sc-subq-label">${sq.label}</div>
            <button class="ans-btn" data-toggle-ans="sc-ans-${i}-${sqi}">Show solution</button>
            <div class="ans-box" id="sc-ans-${i}-${sqi}" style="border-color:var(--yellow)">
              <div style="font-family:'JetBrains Mono',monospace;font-size:12px;color:var(--code);white-space:pre-wrap;line-height:1.7;">${escapeHtml(sq.hint)}</div>
            </div>
          </div>
        `).join('')}
      </div>
    </div>
  `).join('');
}

function escapeHtml(s) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function toggleSC(bodyId, chevId) {
  const body = document.getElementById(bodyId);
  const chev = document.getElementById(chevId);
  body.classList.toggle('open');
  chev.classList.toggle('open');
}

// ===================================
// CHEATSHEET
// ===================================
function buildCheatsheet() {
  const el = document.getElementById('cheat-grid');
  el.innerHTML = DATA.cheatsheet.map(c => `
    <div class="cheat-card">
      <div class="cheat-title">${c.icon || ''} ${c.title}</div>
      ${c.items.map(i => `<div class="cheat-item">${i}</div>`).join('')}
    </div>
  `).join('');
}

// ===================================
// FILL BLANKS
// ===================================
function buildFillBlanks() {
  const el = document.getElementById('fill-list');
  el.innerHTML = DATA.fillBlanks.map((fb, i) => `
    <div class="fb-card">
      <div class="fb-num">${i + 1}.</div>
      <div class="fb-content">
        <div class="fb-q">${fb.q.replace('___', '<span class="fb-blank">___</span>')}</div>
        <button class="ans-btn" data-toggle-ans="fb-${i}">Show answer</button>
        <div class="fb-a" id="fb-${i}">${fb.a}</div>
      </div>
    </div>
  `).join('');
}

function showAllAnswers() {
  DATA.fillBlanks.forEach((_, i) => {
    document.getElementById('fb-' + i).classList.add('show');
  });
}

function hideAllAnswers() {
  DATA.fillBlanks.forEach((_, i) => {
    document.getElementById('fb-' + i).classList.remove('show');
  });
}

// ===================================
// INIT
// ===================================
buildHome();
buildTopics();
buildQuizSetup();
buildCheatsheet();
buildFillBlanks();
buildPastExams();
buildSectionC();
buildProgressTracker();

// ===================================
// EVENT DELEGATION (replaces all onclick= attributes)
// ===================================
(function() {
  // Wire up static nav buttons
  document.querySelectorAll('nav button[data-page]').forEach(btn => {
    btn.addEventListener('click', function() {
      showPage(this.dataset.page, this);
    });
  });

  // Topics page static buttons
  var btnExpand = document.getElementById('btn-expand-all');
  if (btnExpand) btnExpand.addEventListener('click', expandAll);
  var btnCollapse = document.getElementById('btn-collapse-all');
  if (btnCollapse) btnCollapse.addEventListener('click', collapseAll);

  // Topic search
  var searchInput = document.getElementById('topic-search');
  if (searchInput) searchInput.addEventListener('input', function() { filterTopics(this.value); });

  // Quiz filter buttons
  document.querySelectorAll('.quiz-opt[data-filter]').forEach(btn => {
    btn.addEventListener('click', function() { setQuizFilter(this.dataset.filter, this); });
  });

  // Quiz control buttons
  var btnStart = document.getElementById('btn-start-quiz');
  if (btnStart) btnStart.addEventListener('click', startQuiz);
  var btnSelectAll = document.getElementById('btn-select-all-topics');
  if (btnSelectAll) btnSelectAll.addEventListener('click', selectAllTopics);
  var btnDeselectAll = document.getElementById('btn-deselect-all-topics');
  if (btnDeselectAll) btnDeselectAll.addEventListener('click', deselectAllTopics);
  var btnExitQuiz = document.getElementById('btn-exit-quiz');
  if (btnExitQuiz) btnExitQuiz.addEventListener('click', resetQuiz);
  var btnNext = document.getElementById('next-btn');
  if (btnNext) btnNext.addEventListener('click', nextQuestion);
  var btnRetry = document.getElementById('btn-retry-quiz');
  if (btnRetry) btnRetry.addEventListener('click', resetQuiz);
  var btnReviewTopics = document.getElementById('btn-review-topics');
  if (btnReviewTopics) btnReviewTopics.addEventListener('click', function() {
    showPage('topics', document.querySelector('nav button[data-page="topics"]'));
  });

  // Fill blanks buttons
  var btnShowAll = document.getElementById('btn-show-all-answers');
  if (btnShowAll) btnShowAll.addEventListener('click', showAllAnswers);
  var btnHideAll = document.getElementById('btn-hide-all-answers');
  if (btnHideAll) btnHideAll.addEventListener('click', hideAllAnswers);

  // Master delegated click handler for all dynamic content
  document.addEventListener('click', function(e) {
    var el = e.target.closest('[data-goto-topic],[data-toggle-topic],[data-toggle-ans],[data-mark-done],[data-toggle-progress],[data-toggle-ts],[data-select-opt],[data-toggle-exam-q],[data-toggle-sc]');
    if (!el) return;

    // Home topic card â†’ go to topic
    if (el.dataset.gotoTopic) {
      goToTopic(el.dataset.gotoTopic);
      return;
    }

    // Topics: expand/collapse topic
    if (el.dataset.toggleTopic) {
      toggleTopic(el.dataset.toggleTopic);
      return;
    }

    // Show/hide answer box (topics, section C, fill blanks)
    if (el.dataset.toggleAns) {
      var ansEl = document.getElementById(el.dataset.toggleAns);
      if (!ansEl) return;
      ansEl.classList.toggle('show');
      el.textContent = ansEl.classList.contains('show') ? 'Hide answer' : (el.textContent.includes('solution') ? 'Show solution' : 'Show answer');
      return;
    }

    // Mark topic as done
    if (el.dataset.markDone) {
      markDone(el.dataset.markDone, el);
      return;
    }

    // Progress tracker toggle
    if (el.dataset.toggleProgress) {
      toggleProgress(el.dataset.toggleProgress);
      return;
    }

    // Quiz topic select
    if (el.dataset.toggleTs) {
      toggleTopicSelect(el.dataset.toggleTs);
      return;
    }

    // Quiz answer option
    if (el.dataset.selectOpt !== undefined) {
      selectOpt(parseInt(el.dataset.selectOpt));
      return;
    }

    // Past exam question toggle
    if (el.dataset.toggleExamQ) {
      toggleExamQ(el.dataset.toggleExamQ, el.dataset.toggleExamChev);
      return;
    }

    // Section C toggle
    if (el.dataset.toggleSc) {
      toggleSC(el.dataset.toggleSc, el.dataset.toggleScChev);
      return;
    }
  });
})();

